[package]
name = "calorie-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "20.0.0"
chrono = "0.4.31"

[dev_dependencies]
soroban-sdk = { version = "20.0.0" }

[lib]
crate-type = ["cdylib"]
